### ISSUE TITLE
give Kayla why we chose this project/dataset

### ISSUE THREAD

**Issue by raycerna** [Jules-Ray-Kayla-Bert-Capstone-FiFA/fifa#8]

**Comment by raycerna** [comment]
I chose this data set because

**Comment by Kayfj41901** [comment]
Here is an example from a previous project of what an answer looks like: 
I am interested in this project because I believe employee retention is a key component of building a successful business. I feel fortunate to live in a time where this type of scientific research is even possible! In the last decade new businesses' have emerged that offer their employees excellent salaries, benefits, stock-options, and working conditions. Many of these businesses, that forewent the traditional approach of paying the CEO six figures, (and the workers 'as little as possible'), have grown into very successful companies. While this dataset is a ficticious dataset created by IBM data scientists, I believe it was carefully designed to be a good representation of actual factors of attrition(I am hoping it is loosely 'based on' their internal data). I also believe IBM is an excellent company with excellent benefits. I believe I will see, within the many features, how their benefit's package supports employee retention. Through this evidence, I hope more companies will be encouraged to invest more in their own people; knowing that what is supportive of the people is supportive of the success of the organization.

**Comment by EribertoContreras** [comment]
Eriberto Contreras:
 This project peaked my interest because it gave me the opportunity to challenge my data science skills in a subject matter that I had no experience with prior. I hope to gain insight on to how teams budget their players and on how the wages range based on skillsets. I am excited to work on data set that comes from such globally known sport and organization as big as FIFA. I hope this project will capture the attention of Data Scientist and FIFA fans and give them a fun learning experience.

**Comment by JulesMorris** [comment]
I chose this project because I am passionate about one of the most intense, inclusive, fast-paced, and exhilarating games on Earth. I have been a fan of the game since I was young, and was excited about the possibility of combining some of the worlds most-famous players with my love of machine learning and predictive algorithms. This is a project that will capture the imagination of everyone who has a love of the game, the. players, or data science.
